WDIP-16: enable hotkeys for selecting flyaway menu options
adamlerer/webDiplomacy pull request #126
Opened 2022-06-29 17:02 UTC by utiq

Re-openning #115

2022-07-01 13:48 UTC, adamlerer commented
I think there's still a problem here: the hotkeys need to differentiate move vs "move via" since sometimes both are possible (and you can't just default to "move via").

2022-07-18 01:36 UTC, adamlerer requested changes
I heard requests again from the players for this feature, so lets get it merged.

2022-07-18 01:36 UTC, adamlerer commented on botgamecreate.php
> +		// $tabl = $DB->sql_tabl("SELECT id FROM wD_Users WHERE type LIKE '%bot%' ".($input['variantID']==15?" AND username='FairBot' ":"")." LIMIT ".$botNum);
Why did you comment this out?

2022-07-18 01:36 UTC, adamlerer commented on beta-src/src/components/map/components/WDFlyoutContainer.tsx
> +  useKeyPressEvent("c", fleetAndSeaAction);
Here's explicitly what I think this should look like to give correct behavior for vias.

```suggestion
  const canVia: boolean =
    unit?.unit?.type === "Army" &&
    legalOrders.legalViasByUnitID[order.unitID].length > 0;
  };

  useKeyPressEvent("h", () => clickHandler("Hold"));
  useKeyPressEvent("d", () => clickHandler("Hold"));
  useKeyPressEvent("m", () => clickHandler("Move"));
  useKeyPressEvent("a", () => clickHandler("Move"));
  useKeyPressEvent("v", () => canVia && clickHandler("Move", "Yes"));
  useKeyPressEvent("s", () => clickHandler("Support"));
  useKeyPressEvent("c", () => clickHandler("Convoy"));
```

2022-07-18 15:01 UTC, utiq commented
> I heard requests again from the players for this feature, so lets get it merged.

sounds good, I'll fix the changes requests

2022-07-19 21:59 UTC, utiq commented
@adamlerer I fixed the conflicts and I committed the suggestion you made. Merged.

2022-07-19 21:59 UTC, merged